name: Update Docker Hub Description
# on: release
on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: peterevans/dockerhub-description
          short-description: ${{ github.event.repository.description }}
